### ISSUE TITLE
Get a Tracklist Sample

### ISSUE THREAD

**Issue by sonypsx** [BigGranu/MusicBrainz#5]
Hi,

i recently found your MusicBrainz thing and found it great, but i struggle how to get a tracklist from a specific album with your project.

Can you please provide me a sample in VB how to do it?

Thank you very much!

regards
sonypsx

**Comment by BigGranu** [comment]
Sorry for the late response.
With this dll is not possible. It lacks a Lookup. Please use the new [MusicApiCollection](https://www.nuget.org/packages/MusicApiCollection/)

Then you can do

```
Dim releasList = MusicApiCollection.Sites.MusicBrainz.Search.ReleaseGroup(release:="Lotus", artist:="Santana").Data.Data.FirstOrDefault().Releaselist

Dim tracks = MusicApiCollection.Sites.MusicBrainz.Lookup.Release(releasList.Release.FirstOrDefault().Id).Data.FirstOrDefault().Mediumlist

For Each medium IN tracks.Medium
   Console.WriteLine(medium.Format & " " & medium.Position)
   For Each track In medium.Tracklist.Track
      Console.WriteLine(String.Format("{0} {1} {2}", track.Number, track.Recording.Title, track.Length))
   Next          
Next
```

**Comment by sonypsx** [comment]
Hello Biggranu!

Thats looking awesome!
Thank you very much - can't wait to test it!

P.s. i hope you simplify the use of discogs API as well, because the current thing is ... you know what i mean!

Best regards
sonypsx
